name: Deploy Git Hub Pages
#run-name: Test GitHub Actions 🚀
on:
  push:
    branches:
      - master

jobs:
  Build-App:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --if-present

      - name: Check environment variable
        if: ${{ secrets.DEPLOY_PLATFORM == "github" }}
        run: echo "Plataforma é github"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TESTE_CI }}
          publish_dir: ./dist

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with: 
          github-token: ${{ secrets.TESTE_CI }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: 'dist'

      # - name: Deploy to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TESTE_CI }}
      #   with:
      #     BRANCH: master
      #     FOLDER: dist/
