name: Deploy Netlify
run-name: Deploy Netlify 🚀
on:
  push:
    branches:
      - master

jobs:
  Build-and-Deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --if-present

      - name: Build
        run: npm run build

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.0.0
      #   with: 
      #     publish-dir: dist
      #     github-token: ${{ secrets.TESTE_CI }}
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: config directory
        run: |
          # mv ./dist ./home/runner/work/ci_cd
          ls 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TESTE_CI }}
          publish_dir: dist

